# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rangoMin', models.IntegerField()),
                ('rangoMax', models.IntegerField()),
                ('ayuda', models.IntegerField()),
                ('orden', models.BooleanField(default=True)),
                ('numPorOP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('contrasena', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estadistica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroAciertos', models.IntegerField()),
                ('numeroFallos', models.IntegerField()),
                ('nivel', models.IntegerField(blank=True)),
                ('tipoOperacion', models.IntegerField()),
                ('fechaReporte', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Docente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=400)),
                ('configuracion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Configuracion')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=400)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaInicio', models.DateTimeField(auto_now_add=True)),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Alumno')),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Juego')),
            ],
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habilitado', models.BooleanField(default=True)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Texto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='texto',
            name='tipoTexto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Tipo_Texto'),
        ),
        migrations.AddField(
            model_name='estadistica',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Sesion'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Grupo'),
        ),
    ]
