# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=30)),
                ('grupo', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Desempeno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroAciertos', models.IntegerField()),
                ('numeroFallos', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('tipoOperacion', models.CharField(max_length=5)),
                ('fechaReporte', models.DateTimeField(auto_now_add=True)),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Historias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=400)),
                ('tipoMascota', models.CharField(max_length=5)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SabiasQue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=400)),
                ('habilitado', models.BooleanField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('fechaInicio', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='desempeno',
            name='idSesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Sesion'),
        ),
    ]
