# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 20:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest_pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historias',
            name='nivel',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
