# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-08 06:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest_pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=400)),
                ('habilitado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('identificacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=355)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupoId', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Docente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=400)),
                ('descripcion', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='alumno',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Grupo'),
        ),
        migrations.AddField(
            model_name='docente',
            name='permisos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Permisos'),
        ),
        migrations.AddField(
            model_name='desempeno',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Grupo'),
            preserve_default=False,
        ),
    ]
