# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest_pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='nivel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='texto',
            name='tipoMascota',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='texto',
            name='tipoOperacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='juego',
            name='configuracion',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='apiRest_pets.Configuracion'),
        ),
    ]
