# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest_pets', '0003_auto_20180331_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='id',
            new_name='identificacion',
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='contrasena',
            new_name='password',
        ),
        migrations.AddField(
            model_name='docente',
            name='rol',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docente',
            name='correo',
            field=models.CharField(max_length=355),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nombre',
            field=models.CharField(max_length=300),
        ),
    ]
