# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-21 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiRest_pets', '0004_auto_20180520_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='rol',
            field=models.BooleanField(default=False),
        ),
    ]
